# Commands to start on workspace startup
tasks:
  - name: tailscaled
    command: sudo tailscaled
  - name: tailscale
    command: |
      sudo -E tailscale up \
        --login-server=https://hs.hugodutka.com \
        --auth-key=$TAILSCALE_PREAUTHKEY \
        --hostname=gitpod-hocus
  - name: dev-env setup
    init: yarn install && npm run dev-prebuild && ops/bin/prepare.sh
    command: |
      ops/bin/link.sh && ops/bin/up.sh && npm run dev
# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 4200
    onOpen: ignore
vscode:
  extensions:
    - Prisma.prisma
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - GitHub.copilot
    - firsttris.vscode-jest-runner
    - dcortes92.FreeMarker
