version: "3"
services:
  agent:
    container_name: agent
    image: worker-dev
    restart: "no"
    privileged: true
    ports:
      - 8822:22
    volumes:
      - "${REPO_DIR}:/app"
      - "${HOCUS_RESOURCES_DIR}:/srv/jailer"
      - /dev/kvm:/dev/kvm
    command: sleep infinity
